# **Assignment 3**

**Create a numpy array starting from 2 till 50 with a stepsize of 3.**

## **ANSWER**

In [ ]:

# importing numpy with alias name
import numpy as np

# creating a array using numpy arange
arr = np.arange(2, 50, 3)

# printing array
print(arr)

array([2, 5, 6, 9, 7, 8])

# **ANSWER 2**

In [21]:
#importing numpy with alias name
import numpy as np

#creating 2 empty lists
list_1 = []
list_2 = []

#getting values from user for list_1
for i in range(5):
  x=int(input("\nEnter values for list 1: "))
  list_1.append(x)

#print list_1
print("list 1", list_1)

#getting values from user for list_2
for i in range(5):
  x=int(input("\nEnter values for list 2: "))
  list_2.append(x)
  
#print list_2
print("list 2", list_2)
print(" ")

#converting lists 1 and list 2 to numpy arrays and printing arrays
array_1 = np.array(list_1)
print("array 1: ", array_1)
array_2 = np.array(list_2)
print("array 2: ", array_2)

#Concatenation of array 1 and array 2
arr_concat = np.concatenate((array_1, array_2))

#printing new array after concatenation
print("Array after concatenation is : ", arr_concat)

#sorting of concatenated array
print("sorted array is:", np.sort(arr_concat))



Enter values for list 1: 2

Enter values for list 1: 14

Enter values for list 1: 63

Enter values for list 1: 85

Enter values for list 1: 21
list 1 [2, 14, 63, 85, 21]

Enter values for list 2: 33

Enter values for list 2: 44

Enter values for list 2: 88

Enter values for list 2: 45

Enter values for list 2: 69
list 2 [33, 44, 88, 45, 69]
 
array 1:  [ 2 14 63 85 21]
array 2:  [33 44 88 45 69]
Array after concatenation is :  [ 2 14 63 85 21 33 44 88 45 69]
sorted array is: [ 2 14 21 33 44 45 63 69 85 88]


# **QUESTION 3**

**Write a code snippet to find the dimensions of a ndarray and its size.**

# **ANSWER**

In [38]:
# importing numpy as np
import numpy as np

# creating a 2d array
arr = np.array([[11,25,33,77],[14,39,55,37]])
print(arr)

#calculating diamension of ndarray
print("\nDimensions of array : ", arr.ndim)
 
# Printing size of array
print("\nSize of array : ", arr.size)

[[11 25 33 77]
 [14 39 55 37]]

Dimensions of array :  2

Size of array :  8


# **QUESTION 4**

**How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims**

# **ANSWER**

In [36]:
#importing numpy
import numpy as np

# creating a 1d array
arr = np.arange(20)

#printing shape of array
print("\nShape of Array :",arr.shape)

# converting using newaxis in row wise
row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)

# converting using newaxis in column wise
col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)


Shape of Array : (20,)

Shape of 2d Array in row major : (1, 20)

Shape of 2d Array in column major : (20, 1)
